%%
%% nfs4_svc was generated by erpcgen (do not edit)
%% date: Aug 17 00:23:43 2020
%%
-module(nfs4_svc).
-include("nfs4.hrl").
-export([nfs4_program_4/5]).
-export([nfs4_callback_1/5]).
-export([init/1, handle_call/3, handle_cast/2, 
         handle_info/2, terminate/2]).

init(Args) ->
    nfs4_server:init(Args).

handle_call(Req, From, S) ->
    nfs4_server:handle_call(Req, From, S).

handle_cast(Req, S) ->
    nfs4_server:handle_cast(Req, S).

handle_info(Req, S) ->
    nfs4_server:handle_info(Req, S).

terminate(Reason, S) ->
    nfs4_server:terminate(Reason, S).

nfs4_program_4(Proc, Bin, Offset, Clnt, State) ->
    case Proc of
        0 ->
            case catch nfs4_server:nfsproc4_null_4(Clnt, State) of
                {reply, Res, NState} ->
                    {success, [], NState};
                Else ->
                    Else
            end;
        1 ->
            {_1, _2} = nfs4_xdr:dec_COMPOUND4args(Bin, Offset),
            case
                catch nfs4_server:nfsproc4_compound_4(_1, Clnt, State)
            of
                {reply, Res, NState} ->
                    {success, nfs4_xdr:enc_COMPOUND4res(Res), NState};
                Else ->
                    Else
            end
    end.

nfs4_callback_1(Proc, Bin, Offset, Clnt, State) ->
    case Proc of
        0 ->
            case catch nfs4_server:cb_null_1(Clnt, State) of
                {reply, Res, NState} ->
                    {success, [], NState};
                Else ->
                    Else
            end;
        1 ->
            {_1, _2} = nfs4_xdr:dec_CB_COMPOUND4args(Bin, Offset),
            case catch nfs4_server:cb_compound_1(_1, Clnt, State) of
                {reply, Res, NState} ->
                    {success, nfs4_xdr:enc_CB_COMPOUND4res(Res), NState};
                Else ->
                    Else
            end
    end.
